### ISSUE TITLE
Generator acts really weird when scaffolding

### ISSUE THREAD

**Issue by aendra-rininsland** [yeoman/generator-webapp_DEPRECATED#384]
I'm guessing this is some kind of regressive issue caused by a recent commit (Was working fine as of last week), but whenever I try to scaffold out something, the generator goes utterly haywire:

![screen shot 2014-05-29 at 14 22 56](https://cloud.githubusercontent.com/assets/185041/3117833/6e54e966-e734-11e3-87de-cd7b06a64bb0.png)

If I continue, it then conflicts with bower.json and asks if I want to overwrite it. Doing so yields the scaffold, but `npm install` hasn't been run, and only `chai` and `mocha` are in the bower_components directory.

Note that this is the case regardless of whether I use the repo version or install the one from npm.org.

**Comment by aendra-rininsland** [comment]
Okay, it's 3c0360baf85580f773bf48600dcf57a6039ec16d that breaks it, at least on Mac OS X 10.9.3. Everything  works fine in 63b821f49fa1122ea562a6d3436917a46f76a968.

**Comment by silvenon** [comment]
Confirmed, mine is infected too. Let's see...

**Comment by silvenon** [comment]
A fix for this issue is announced in https://github.com/yeoman/generator/issues/526#issuecomment-44597899.

**Comment by eddiemonge** [comment]
@aendrew are you using the git version of this generator?

**Comment by aendra-rininsland** [comment]
@eddiemonge Just replicated on my home machine using generator-webapp Git version at commit c02350c4c94b71b1d3d7851503acb3714cca5652, though was working previously with the npm version. I was having the same issue with the npm version at work, not sure why. `Yo` version 1.1.2, by the way. Now trying the Git version of Yo...

Update: Yep, same issue using the Git version of Yo, both at HEAD and [the commit referenced there](https://github.com/yeoman/yo/commit/fcca53c32bd9c99e93435c91c90eca830c54e18e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R420). All of this is at generator-webapp HEAD, btw.

**Comment by aendra-rininsland** [comment]
@silvenon Apologies if I'm being daft, but I don't quite understand. I've tried updating Yo, yeoman-generator, using the git versions of both. Should I be using yeoman-generator 0.17.0-pre.3 or something? Thanks!

**Comment by silvenon** [comment]
AFAIK a new version of yo needs to be released, then yeoman-generator will be updated, then generator-webapp can be updated :smiley:

**Comment by aendra-rininsland** [comment]
@silvenon Ah, okay! Makes sense; thanks!

**Comment by KingScooty** [comment]
Has this issue been fixed yet?

**Comment by silvenon** [comment]
No :( @sindresorhus @passy @eddiemonge it would be so awesome if anyone can fix this, the generator is unusable. Should we just downgrade yeoman-generator?

**Comment by eddiemonge** [comment]
We should fix the bugs in yeoman-generator and yo and release newer versions of those. the only blockers are the failing tests

**Comment by sindresorhus** [comment]
@eddiemonge have you talked to @SBoudrias about the bug in yeoman-generator?

**Comment by eddiemonge** [comment]
@sindresorhus i think we are waiting on you. We need a new release of `yo` which is currently blocked by https://github.com/yeoman/yo/issues/171 and we need a new release of `yeoman-generator` which I think is blocked by https://github.com/yeoman/generator/issues/572

**Comment by aendra-rininsland** [comment]
Note that a new release might need to be pushed to npm — doing a `npm update -g generator-webapp` didn't fix it, though using the Git version of `generator-webapp` did (Thanks, by the way!).
